import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { semiMajorAxisAu, periodDays, luminosity, equilibriumTemp, habitableZone, inHabitableZone, esi, overlapArea, radiusRatio, impactParameter, fluxDrop, transitDurationHours, separation, simulateTransit, MOLECULES, transmissionSpectrum, detectMolecules, wavelengthGrid, addNoise, scaleHeightKm, surfaceGravity, orbitRadiusUnits, planetVisualRadius, starVisualRadius, starColor, makeCatalog, countsByYear, discoveriesUpTo, R_SUN_AU } from "../src/index.ts";
import type { System } from "@nebula/schemas";
const systems: System[] = JSON.parse(readFileSync(new URL("../../../data/generated/systems.json", import.meta.url), "utf8"));
const SUN = { radiusSolar: 1, massSolar: 1 };

describe("orbits and temperature", () => {
  it("Kepler's third law: 1 year at 1 solar mass is 1 AU, and the round trip is the identity", () => { expect(semiMajorAxisAu(365.25, 1)).toBeCloseTo(1); expect(periodDays(semiMajorAxisAu(11.6, 0.9), 0.9)).toBeCloseTo(11.6); expect(semiMajorAxisAu(365.25, 4)).toBeCloseTo(4 ** (1 / 3)); });
  it("the Sun's equilibrium temperature at 1 AU is about 255 K and the luminosity is 1", () => { expect(equilibriumTemp(5772, 1, 1)).toBeGreaterThan(250); expect(equilibriumTemp(5772, 1, 1)).toBeLessThan(260); expect(luminosity(1, 5772)).toBeCloseTo(1); expect(luminosity(0.5, 3500)).toBeLessThan(0.05); });
  it("habitable zone brackets Earth for the Sun and scales with sqrt of luminosity", () => { const z = habitableZone(1); expect(z.inner).toBeLessThan(1); expect(z.outer).toBeGreaterThan(1); expect(inHabitableZone(1, 1)).toBe(true); expect(inHabitableZone(1, 0.5)).toBe(false); expect(inHabitableZone(1, 2)).toBe(false); expect(habitableZone(4).inner).toBeCloseTo(2 * habitableZone(1).inner); });
  it("ESI is 1 for Earth, falls with distance from Earth, and stays within 0..1", () => { expect(esi(1, 255, 1)).toBe(1); expect(esi(1.5, 255, 1)).toBeLessThan(1); expect(esi(1, 400, 1)).toBeLessThan(esi(1, 280, 1)); for (const v of [esi(10, 1500, 50), esi(0.2, 60, 0.01)]) { expect(v).toBeGreaterThanOrEqual(0); expect(v).toBeLessThan(1); } });
});
describe("transit geometry", () => {
  it("overlap area: none apart, full inside, half-ish at the limb, symmetric in nothing but the physics", () => { expect(overlapArea(0.1, 1.2)).toBe(0); expect(overlapArea(0.1, 0.5)).toBeCloseTo(Math.PI * 0.01); expect(overlapArea(0.1, 1.0)).toBeGreaterThan(0.1 * 0.1 * Math.PI * 0.45); expect(overlapArea(0.1, 1.0)).toBeLessThan(Math.PI * 0.01 * 0.55); });
  it("depth is about k squared at the centre and shrinks toward the limb (limb darkening)", () => { const k = 0.01; expect(fluxDrop(k, 0)).toBeGreaterThan(k * k); expect(fluxDrop(k, 0)).toBeLessThan(k * k * 1.3); expect(fluxDrop(k, 0.9)).toBeLessThan(fluxDrop(k, 0)); expect(fluxDrop(k, 2)).toBe(0); });
  it("an Earth around the Sun: depth near 84 ppm, duration near 13 hours at 1 AU", () => { const k = radiusRatio(1, 1); expect(k * k * 1e6).toBeCloseTo(84, 0); const h = transitDurationHours(365.25, 1, 1, k, 90); expect(h).toBeGreaterThan(12.5); expect(h).toBeLessThan(13.5); });
  it("the numeric light curve agrees with the analytic duration", () => {
    const r = simulateTransit({ radiusEarth: 11, periodDays: 3.5, inclinationDeg: 89.5, noisePpm: 0, star: SUN, samples: 4000 }), below = r.times.filter((_, i) => r.flux[i] < 1 - 1e-6), width = (below.at(-1)! - below[0]) * 24;
    expect(Math.abs(width - r.durationH) / r.durationH).toBeLessThan(0.03); expect(Math.min(...r.flux)).toBeCloseTo(1 - r.depthPpm / 1e6, 3); });
  it("the curve is symmetric about mid-transit and flat outside it", () => { const r = simulateTransit({ radiusEarth: 5, periodDays: 10, inclinationDeg: 89.9, noisePpm: 0, star: SUN, samples: 241 }), n = r.flux.length; for (let i = 0; i < 40; i++) expect(r.flux[i]).toBeCloseTo(r.flux[n - 1 - i], 6); expect(r.flux[0]).toBe(1); });
  it("tilting the orbit removes the transit, with a reason", () => { const base = { radiusEarth: 11, periodDays: 3.5, noisePpm: 0, star: SUN }; expect(simulateTransit({ ...base, inclinationDeg: 89.9 }).transits).toBe(true); const off = simulateTransit({ ...base, inclinationDeg: 82 }); expect(off.transits).toBe(false); expect(off.depthPpm).toBe(0); expect(off.durationH).toBe(0); expect(off.reason).toMatch(/No transit/); expect(Math.min(...off.flux)).toBe(1); });
  it("grazing transits are shallower and shorter than central ones", () => { const base = { radiusEarth: 11, periodDays: 3.5, noisePpm: 0, star: SUN }, c = simulateTransit({ ...base, inclinationDeg: 90 }), g = simulateTransit({ ...base, inclinationDeg: 86.8 }); expect(g.transits).toBe(true); expect(g.depthPpm).toBeLessThan(c.depthPpm); expect(g.durationH).toBeLessThan(c.durationH); });
  it("noise is seeded and has the requested size", () => { const a = simulateTransit({ radiusEarth: 3, periodDays: 8, inclinationDeg: 90, noisePpm: 500, star: SUN, seed: 4, samples: 2000 }), b = simulateTransit({ radiusEarth: 3, periodDays: 8, inclinationDeg: 90, noisePpm: 500, star: SUN, seed: 4, samples: 2000 }); expect(a.flux).toEqual(b.flux); const out = a.flux.slice(0, 200), m = out.reduce((s, v) => s + v, 0) / 200, sd = Math.sqrt(out.reduce((s, v) => s + (v - m) ** 2, 0) / 200) * 1e6; expect(sd).toBeGreaterThan(400); expect(sd).toBeLessThan(600); });
  it("separation: mid-transit is in front at distance b; half an orbit later it is behind", () => { const aRs = 20, f = separation(aRs, 89, 0), bk = separation(aRs, 89, Math.PI); expect(f.front).toBe(true); expect(f.z).toBeCloseTo(aRs * Math.cos((89 * Math.PI) / 180)); expect(bk.front).toBe(false); expect(impactParameter(aRs * 1 * R_SUN_AU, 1, 89)).toBeCloseTo(f.z); });
});
describe("spectra", () => {
  const wl = wavelengthGrid(0.5, 5.5, 600), warm = { radiusEarth: 11, massEarth: 100, teqK: 900, starRadiusSolar: 1, hydrogenRich: true };
  it("scale height grows with temperature and falls with gravity and molecular mass", () => { const g = surfaceGravity(1, 1); expect(g).toBeCloseTo(9.8, 0); expect(scaleHeightKm(300, 28, g)).toBeCloseTo(8.7, 0); expect(scaleHeightKm(600, 28, g)).toBeGreaterThan(scaleHeightKm(300, 28, g)); expect(scaleHeightKm(300, 2.3, g)).toBeGreaterThan(scaleHeightKm(300, 28, g)); });
  it("a molecule's absorption raises the depth at its band and nowhere else", () => { const none = transmissionSpectrum({ ...warm, atmosphere: {} }, wl), h2o = transmissionSpectrum({ ...warm, atmosphere: { H2O: 1 } }, wl), i14 = wl.findIndex((l) => l > 1.4), i3 = wl.findIndex((l) => l > 3.9); expect(h2o[i14]).toBeGreaterThan(none[i14]); expect(h2o[i3]).toBeCloseTo(none[i3], 0); });
  it("detection finds the molecules that are there and not the ones that are absent", () => { const spec = transmissionSpectrum({ ...warm, atmosphere: { H2O: 1, CH4: 1 } }, wl), d = detectMolecules(spec, wl, 20).map((x) => x.molecule); expect(d).toContain("H2O"); expect(d).toContain("CH4"); expect(d).not.toContain("O3"); expect(d).not.toContain("Na"); });
  it("a band shared with another molecule does not report a molecule that is absent: water's 2.7 micrometres does not make carbon dioxide", () => { const spec = transmissionSpectrum({ ...warm, atmosphere: { H2O: 1 } }, wl); expect(detectMolecules(spec, wl, 20).map((x) => x.molecule)).not.toContain("CO2"); const both = transmissionSpectrum({ ...warm, atmosphere: { H2O: 1, CO2: 1 } }, wl); expect(detectMolecules(both, wl, 20).map((x) => x.molecule)).toContain("CO2"); });
  it("heavy noise hides the weak bands", () => { const spec = addNoise(transmissionSpectrum({ ...warm, atmosphere: { H2O: 0.1 } }, wl), 4000, 2); expect(detectMolecules(spec, wl, 4000)).toEqual([]); });
  it("a small rocky planet's bands are far weaker than a hot gas giant's", () => { const small = transmissionSpectrum({ radiusEarth: 1, massEarth: 1, teqK: 260, starRadiusSolar: 1, hydrogenRich: false, atmosphere: { CO2: 1 } }, wl), none = transmissionSpectrum({ radiusEarth: 1, massEarth: 1, teqK: 260, starRadiusSolar: 1, hydrogenRich: false, atmosphere: {} }, wl); const smallDiff = Math.max(...small) - Math.max(...none); expect(smallDiff).toBeLessThan(40); const big = transmissionSpectrum({ ...warm, atmosphere: { H2O: 1 } }, wl); expect(Math.max(...big) - Math.min(...big)).toBeGreaterThan(20 * smallDiff); });
  it("every molecule has bands inside the grid", () => { for (const m of Object.values(MOLECULES)) expect(m.bands.some((b) => b.c >= 0.5 && b.c <= 10)).toBe(true); expect(wl[0]).toBeCloseTo(0.5); expect(wl.at(-1)).toBeCloseTo(5.5); });
});
describe("visual scales", () => { it("are monotonic", () => { for (const f of [orbitRadiusUnits, planetVisualRadius, starVisualRadius]) { let p = -1; for (const x of [0.01, 0.05, 0.3, 1, 5, 30]) { expect(f(x)).toBeGreaterThan(p); p = f(x); } } expect(starColor(3000)[2]).toBeLessThan(starColor(6500)[2]); }); });
describe("catalog and timeline", () => {
  it("is deterministic, has a survey wave, and counts add up", () => { const c = makeCatalog(260), counts = countsByYear(c); expect(makeCatalog(260)).toEqual(c); expect(counts.reduce((a, x) => a + x.count, 0)).toBe(c.length); expect(Math.max(...counts.map((x) => x.count))).toBeGreaterThan(counts[0].count * 5); expect(counts.find((x) => x.count === Math.max(...counts.map((y) => y.count)))!.year).toBeGreaterThanOrEqual(2011); expect(counts.find((x) => x.count === Math.max(...counts.map((y) => y.count)))!.year).toBeLessThanOrEqual(2016); });
  it("discoveries up to a year are cumulative and monotonic", () => { const c = makeCatalog(260); let p = 0; for (let y = 1995; y <= 2026; y += 3) { const n = discoveriesUpTo(c, y).length; expect(n).toBeGreaterThanOrEqual(p); p = n; } expect(discoveriesUpTo(c, 1994)).toEqual([]); expect(discoveriesUpTo(c, 2026)).toHaveLength(c.length); });
});
describe("the generated systems", () => {
  it("are consistent with Kepler's law and the temperature formula", () => { for (const s of systems) for (const p of s.planets) { expect(p.semiMajorAxisAu).toBeCloseTo(semiMajorAxisAu(p.periodDays, s.massSolar), 3); expect(Math.abs(p.equilibriumTempK - equilibriumTemp(s.temperatureK, s.radiusSolar, p.semiMajorAxisAu))).toBeLessThanOrEqual(1.5); } expect(systems.flatMap((s) => s.planets)).toHaveLength(26); });
  it("a mix of types, at least one planet per system transits and at least one is in the habitable zone", () => { const all = systems.flatMap((s) => s.planets.map((p) => ({ s, p }))); expect(new Set(all.map((x) => x.p.kind)).size).toBe(6); for (const s of systems) expect(s.planets.some((p) => simulateTransit({ radiusEarth: p.radiusEarth, periodDays: p.periodDays, inclinationDeg: p.inclinationDeg, noisePpm: 0, star: s }).transits)).toBe(true); expect(all.filter((x) => inHabitableZone(luminosity(x.s.radiusSolar, x.s.temperatureK), x.p.semiMajorAxisAu)).length).toBeGreaterThanOrEqual(3); });
});
